agent:
  name: diayn_gher
  class: agent.diayn_gher.DIAYNGHERAgent
  params:
    obs_dim: ??? # to be specified later
    action_dim: ??? # to be specified later
    action_range: ??? # to be specified later
    skill_dim: 4 # to be specified later.
    obs_dim_weights: [1, 1]
    skill_type: discrete 
    device: ${device}
    critic_cfg: ${double_q_critic}
    actor_cfg: ${diag_gaussian_actor}
    discriminator_cfg: ${discriminator}
    discount: 0.99
    init_temperature: 0.1
    alpha_lr: 1e-4
    alpha_betas: [0.9, 0.999]
    actor_lr: 1e-4
    actor_betas: [0.9, 0.999]
    actor_update_frequency: 1
    critic_lr: 1e-4
    critic_betas: [0.9, 0.999]
    critic_tau: 0.005
    critic_target_update_frequency: 2
    discriminator_lr: 1e-4
    discriminator_betas: [0.9, 0.999]
    discriminator_update_frequency: 1
    batch_size: 1024
    learnable_temperature: true
    log_frequency: 10000
    log_save_tb: true
    name_env : AntEnv
    max_replay_buffer_size: 5e6
    plotter: None
    render_eval_paths: false
    use_automatic_entropy_tuning: true 

    
double_q_critic:
  class: agent.critic.DoubleQCritic
  params:
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    skill_dim: ${agent.params.skill_dim}
    hidden_dim: 1024
    hidden_depth: 2
    
discriminator:
  class: agent.discriminator.Discriminator
  params:
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    skill_dim: ${agent.params.skill_dim}
    skill_type: ${agent.params.skill_type}
    hidden_dim: 1024
    hidden_depth: 2

diag_gaussian_actor:
  class: agent.actor.DiagGaussianActor
  params:
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    skill_dim: ${agent.params.skill_dim}
    hidden_depth: 2
    hidden_dim: 1024
    log_std_bounds: [-5, 2]
